// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3FtEqV9TQsNfjyG761FtHc75_j2ggYA',
    appId: '1:561389227109:android:59ef8fbe2cf4050737ca8c',
    messagingSenderId: '561389227109',
    projectId: 'folio-4265a',
    storageBucket: 'folio-4265a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWUGXAkyhFu2sA-pE9jPzn_fZp9cQjxB0',
    appId: '1:561389227109:ios:f59e19a6a67adf6b37ca8c',
    messagingSenderId: '561389227109',
    projectId: 'folio-4265a',
    storageBucket: 'folio-4265a.appspot.com',
    iosClientId: '561389227109-vt6e80cstu589b73ek776bmp1obhi1mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.folio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWUGXAkyhFu2sA-pE9jPzn_fZp9cQjxB0',
    appId: '1:561389227109:ios:f59e19a6a67adf6b37ca8c',
    messagingSenderId: '561389227109',
    projectId: 'folio-4265a',
    storageBucket: 'folio-4265a.appspot.com',
    iosClientId: '561389227109-vt6e80cstu589b73ek776bmp1obhi1mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.folio',
  );
}
